export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_OPTIONS = 'GET_CATEGORIES_OPTIONS';

export const GET_EXPENDITURES_REQUEST = 'GET_EXPENDITURES_REQUEST';
export const GET_EXPENDITURES_SUCCESS = 'GET_EXPENDITURES_SUCCESS';
export const GET_EXPENDITURES_FAILURE = 'GET_EXPENDITURES_FAILURE';

export const UPDATE_EXPENDITURES_REQUEST = 'UPDATE_EXPENDITURES_REQUEST';
export const UPDATE_EXPENDITURES_SUCCESS = 'UPDATE_EXPENDITURES_SUCCESS';
export const UPDATE_EXPENDITURES_FAILURE = 'UPDATE_EXPENDITURES_FAILURE';

export const REMOVE_EXPENDITURE_REQUEST = 'REMOVE_EXPENDITURE_REQUEST';
export const REMOVE_EXPENDITURE_SUCCESS = 'REMOVE_EXPENDITURE_SUCCESS';
export const REMOVE_EXPENDITURE_FAILURE = 'REMOVE_EXPENDITURE_FAILURE';

export const ADD_EXPENDITURE_REQUEST = 'ADD_EXPENDITURE_REQUEST';
export const ADD_EXPENDITURE_SUCCESS = 'ADD_EXPENDITURE_SUCCESS';
export const ADD_EXPENDITURE_FAILURE = 'ADD_EXPENDITURE_FAILURE';

export const SET_CURRENT_EXPENDITURE = 'SET_CURRENT_EXPENDITURE';

export const TOGGLE_EDIT_POPUP = 'TOGGLE_EDIT_POPUP';
export const TOGGLE_REMOVE_POPUP = 'TOGGLE_REMOVE_POPUP';
export const TOGGLE_ADD_POPUP = 'TOGGLE_ADD_POPUP';


export const FILTER_EXPENDITURES = 'FILTER_EXPENDITURES';
export const UPDATE_EXPENDITURE = 'UPDATE_EXPENDITURE';
export const DELETE_EXPENDITURE = 'DELETE_EXPENDITURE';
export const ADD_EXPENDITURE = 'ADD_EXPENDITURE';


